# Nginx resmi imajını temel al
FROM nginx:latest

# HTML dosyalarını Nginx'in varsayılan dizinine kopyala
COPY ./html /usr/share/nginx/html

# COPY ./nginx.conf /etc/nginx/nginx.conf

# Konteynerin 80 portunu dışarıya aç
EXPOSE 80
